source "https://supermarket.getchef.com"
source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'supervisor'
cookbook 'gearman', '~> 0.0.1'
cookbook 'yum'
cookbook 'bluepill'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'apache2'
cookbook 'nginx'
cookbook 'php'
cookbook 'mysql'
cookbook 'application_git'
cookbook 'nodejs'
cookbook 'imagemagick'
cookbook 'phpapp', path: 'phpapp'
cookbook 'alb_support', path: 'alb_support'
cookbook 'newrelic', path: 'newrelic_cookbook'
cookbook 'phpmyadmin', path: 'phpmyadmin_cookbook'